### ISSUE TITLE
Example using different project layout

### ISSUE THREAD

**Issue by sormuras** [forax/pro#19]
Hi Rémi,

I'm in the process of making https://github.com/sormuras/application-junit5-jdk9-demo work with **pro** locally and on Travis CI. I already achieved the goal in a branch, where I moved the module sources according to the conventions expected by **pro**. See the branch source here: https://github.com/sormuras/application-junit5-jdk9-demo/tree/pro and the working build at: https://travis-ci.org/sormuras/application-junit5-jdk9-demo/builds/222769148

Now, I want to configure **pro** to work with the "other" layout found in the master branch. The project layout looks like:
![project layout](https://raw.githubusercontent.com/sormuras/application-junit5-jdk9-demo/pro/readme-junit5-idea-java9-project-tree-overview.png)

I guess, I have to configure the "resolver" plugin, right?

Like:
```
set("resolver.modulePath", list("application.api/src", "integration/src"))
```
Or do I need to set it up in "convention" and/or "compiler"?

**Comment by forax** [comment]
I would like to answer, just change the convention, but that's not currently possible,
the plan is to let plugins to listen part of the configuration and re-configure itself when it changes,
but this is not currently implemented, you have to configure every plugins :(

**Comment by sormuras** [comment]
I tend to go with the "pro" convention layout and adapt the IDE(a) project files...

**Comment by forax** [comment]
That's the purpose of conventions :)

**Comment by sormuras** [comment]
Conventions will prevail.
