### ISSUE TITLE
/env in "build.pro" restarts build

### ISSUE THREAD

**Issue by sormuras** [forax/pro#22]
I'm not sure whether this is intended behaviour of `jshell` or a flaw in **pro**:

`build.pro`:
```
System.out.println("java runtime: " + Runtime.version())
/env -class-path deps/any.jar
```

You get the `System.out.println` line twice.

Another example: https://github.com/sormuras/application-junit5-jdk9-demo/blob/pro/tests.pro
Heres a pointer to the log: https://travis-ci.org/sormuras/application-junit5-jdk9-demo/builds/223105874#L208

**Comment by forax** [comment]
This is the normal (but surprising) behavior of /ens in jshell.

jshell> /help /env
|  
|  /env
|  
|  View or change the evaluation context.  The evaluation context is the class path,
|  module path, etc.
|  /env
|  	Show the evaluation context displayed as context options.
|  
|  /env [-class-path <path>] [-module-path <path>] [-add-modules <modules>] ...
|  	With at least one option set, sets the evaluation context.  If snippets
|  	have been defined, the execution state is reset with the new
|  	evaluation context and the snippets will be replayed -- the replay is not
|  	shown, however, errors will display.  This is equivalent to: /reload -quiet
|  	For details of context options, see:
|  
|  		/help context
|  
|  	For example:
|  
|  		/env -add-modules com.greetings
