### ISSUE TITLE
User-defined plugins

### ISSUE THREAD

**Issue by fisk** [forax/pro#28]
Is there any way for the user to build their own plugins? In particular, I have some ANTLR4 grammars that need to be source-to-source compiled into Java code to be included in a module.

**Comment by forax** [comment]
The current limitation is that all plugins as to be integrated with pro.
So inside the source of pro, there is a folder plugins, and you can create your own plugin like the runner plugin or the tester plugin and then send me a pull request.

Plugins in the folder "plugins" have their own dependencies in deps but are built by one giant script in https://github.com/forax/pro/blob/master/src/main/java/com.github.forax.pro.bootstrap/com/github/forax/pro/bootstrap/Bootstrap.java

**Comment by forax** [comment]
There is now a method loadPlugin() [1] in Pro that allows pro to load any external plugins which fix this issue.

[1] https://github.com/forax/pro/blob/master/src/main/java/com.github.forax.pro/com/github/forax/pro/Pro.java#L92
