### ISSUE TITLE
Specify source file encoding

### ISSUE THREAD

**Issue by sormuras** [forax/pro#3]
How do I pass a VM option like `-Dfile.encoding=UTF-8` to the compiler?

**Comment by sormuras** [comment]
Forking and building "pro" works like a charm, so I just did a quick `CompilerPlugin.java` hack:
```
    CmdLine cmdLine = gatherAll(JavacOption.class, option -> option.action).apply(javac, new CmdLine());
    cmdLine.addAll("-encoding", "UTF-8");
```

**Comment by forax** [comment]
Hi Christian,
i've just added an option rawArguments to the compiler plugin,
so in the JSON, this snippet should work
  compiler: {
    rawArguments: [  "-Dfile.encoding=UTF8" ]
  }

let me know if it works for you

**Comment by sormuras** [comment]
Ho Rémi! Thanks for the quick fix.
I like the .pro/shell syntax more:
```
set("compiler.rawArguments", list(
     "-encoding", "UTF8"
));
```
