### ISSUE TITLE
Rename test "module-info.java" to...

### ISSUE THREAD

**Issue by sormuras** [forax/pro#39]
As a follow-up from #4 and the just declined https://youtrack.jetbrains.com/issue/IDEA-172647 I think **pro** should use a different name for the test `module-info.java` overlay files. It confuses not only new **pro** users but also other build tools like IDEs.

Is it possible to name those files: `module-info.test`?

The extension `.test` automatically prevents other build tools to include it in their compile process. The dependencies required by the test code has to be supplied manually on the class-path ... for now. Until those tools adopt the merge strategy.

My current work-around is to use `module-info.test` already and move them before and after the **pro** `run` command:
```
java.nio.file.Files.move(
  java.nio.file.Paths.get("src/test/java/foo.bar").resolve("module-info.test"),
  java.nio.file.Paths.get("src/test/java/foo.bar").resolve("module-info.java")
)

run("resolver", "modulefixer", "compiler", "packager", "tester", "runner")

java.nio.file.Files.move(
  java.nio.file.Paths.get("src/test/java/foo.bar").resolve("module-info.java"),
  java.nio.file.Paths.get("src/test/java/foo.bar").resolve("module-info.test")
)
```

**Comment by forax** [comment]
The guy from JetBrain is wrong, you can have several modules with the same name if there are in different folders.
This was designed to enable testing :)

**Comment by sormuras** [comment]
I'll tell them. (:
