### ISSUE TITLE
`pro build test.pro` exit code

### ISSUE THREAD

**Issue by pacien** [forax/pro#65]
`pro build test.pro` returns 0 even when some tests are failing.

It would be nice to return a failed status code for easier integration with CI tools.

**Comment by pacien** [comment]
`.api.Command.execute` already returns a status code.
Maybe should it be returned by `.Pro.run` on the first failure as well.

**Comment by forax** [comment]
The initial idea was to throw an error so jshell that runs the build script will exit with an error code,
but jshell exit with 0 even if there is an error.

You're right that trying to propagate the error code and using
  \exit run(...)
may solve this issue.

**Comment by pacien** [comment]
What about watching for `jdk.jshell.EvalException` through `JShell.onSnippetEvent` and exiting with an error code?

**Comment by forax** [comment]
In that case, the behavior of jshell run by pro and the behavior of a stock jshell will be different,
i would prefer to have only one behavior, testing a build script in jshell is so convenient.

**Comment by forax** [comment]
Fixed !
see https://github.com/forax/pro/commit/94d03b045c71e62b76038acef45cb642eea28987
