### ISSUE TITLE
Enabling preview features

### ISSUE THREAD

**Issue by fwgreen** [forax/pro#66]
I'm experimenting with the Early-Access Amber build of Pro.  I've set the Amber demo as my default JDK and my program builds and runs fine until I try to use any preview features.
```
./src/main/java/web.main/org/fwgreen/app/App.java:5: error: raw string literals are a preview feature and are disabled by default.

        System.out.println(`Hello World`);
                           ^
  (use --enable-preview to enable raw string literals)
```

Adding `--enable-preview` to the compiler arguments yields...
```
error: invalid source release 11 with --enable-preview
  (preview language features are only supported for release 12)
[pro] FAILED !        elapsed time 393 ms
Exception java.lang.Error: command 'compiler' exit with code 2
      at Pro.exit (Pro.java:573)
      at Pro.executeAll (Pro.java:551)
      at Pro.runAll (Pro.java:523)
      at Pro.run (Pro.java:512)
      at Pro.run (Pro.java:480)
      at (#5:1)
```
The commit history shows this as being enabled by default, so I'm wondering if I'm missing something.

**Comment by forax** [comment]
It's enabled by default in the build script not if you compile a source code.
To enable the preview, for the compiler, the docer (the javadoc) and the runner, you have a method `enablePreview`
```
  compiler.enablePreview(true)
  docer.enablePreview(true)
  runner.enablePreview(true)
```

**Comment by forax** [comment]
javadoc seems to require -source 12, `sourceRelease(12)` should work

**Comment by fwgreen** [comment]
That did the trick!  Thank you so much.
