### ISSUE TITLE
Instructions don't work for Mac

### ISSUE THREAD

**Issue by paul-hammant** [forax/pro#69]
```
$ java pro_wrapper.java 
download https://github.com/forax/pro/releases/download/0.11-026/pro-macos-early-access-loom.zip to /Users/paul/.pro/cache/0.11-026/pro-macos-early-access-loom.zip
download https://github.com/forax/pro/releases/download/0.11-026/pro-macos-early-access-loom.zip to /Users/paul/.pro/cache/0.11-026/pro-macos-early-access-loom.zip
download https://github.com/forax/pro/releases/download/0.11-026/pro-macos-early-access-loom.zip to /Users/paul/.pro/cache/0.11-026/pro-macos-early-access-loom.zip
i/o error null from pro_wrapper.retry(pro_wrapper.java:184)
```

There's no download file with `-loom` in it for Mac for 0.11-026/

**Comment by forax** [comment]
Hi paul,
loom, amber and lworld version of pro are only available on Linux actually, mostly because nobody ask for a Mac version.

I know that loom should work on Mac, so let me modify the building pipelines and see if it works

**Comment by paul-hammant** [comment]
That's great if you could :) I you can't let me know and I'll setup some virtualization or get a shell account somewhere to do it.

**Comment by forax** [comment]
The main issue currently is that hg.openjdk.java.net returns Python errors so i've to wait the Oracle ops to fix that :(

If you want to test pro with loom in the meantime you can still use a linux VM.

**Comment by paul-hammant** [comment]
I'll try that out :)

Also, while I'm here, https://forax.github.io/ isn't getting much attention, and it could be :)

**Comment by forax** [comment]
Ok,
it should work on Mac, let me know if there is an issue
[](https://github.com/forax/pro/releases/tag/0.11-027)

**Comment by forax** [comment]
and yes, my blog need more love
