### ISSUE TITLE
Demo follows bad module naming practices

### ISSUE THREAD

**Issue by zyxist** [forax/pro#72]
Hello! Thanks for the project - I was looking around a bit and I noticed that the provided demo follows bad module naming practices.

Due to how JPMS works and how it is related to packages, the recommendation is to name the module, using reverse-DNS convention (and even better = to be identical as the root package to "take over" it, since there is a strong ownership relation between the package and module). However, the demo does something like this:

 * module `printer.logger`, root package `com.acme.printer.logger`
 * module `printer.main`, root package `com.acme.printer.main`
 * etc.

Reference: 

 * https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html - excellent explanation why doing anything else is a bad idea,
 * http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-May/000687.html - by Mark Reinhold, chief Java architect
 * many other readings about modules.

**Comment by forax** [comment]
yes, you are fully right.

I suppose that the shoemaker's son always goes barefoot
Just for fun, if from your second link, you click on the next message, you will find my reply to Mark :)

I will fix that ASAP, thanks

**Comment by forax** [comment]
fixed by https://github.com/forax/pro-demo/commit/bcf89b08f57b29523d21f40836fbd0dc2c9b91ba
