### ISSUE TITLE
Execute permission denied on macOS Catalina

### ISSUE THREAD

**Issue by fwgreen** [forax/pro#74]
From what I can glean, under certain circumstances, Catalina strips executable permissions while unzipping files.  

macOS 10.15.6

**Comment by forax** [comment]
I believe that if you use the wrapper to download pro it will work.

Can you try to cut and paste this in your current directory
  https://github.com/forax/pro/blob/master/wrapper/pro_wrapper.java

and run
  java pro_wrapper.java

**Comment by fwgreen** [comment]
Thanks!
